'use strict';

// 中文词库（Chinese translation table）
// 显示名即数据表主键（utility.js 的 capitalSplit 已被短路为 `return string`，
// 因此 niceName === 表键），所以这里的键就是各数据表的主键。
// 查不到时原样返回英文，因此可以安全地全局挂钩渲染层。

var translator = {};

// 精确匹配：绝大多数显示名都能直接命中
translator.getText = function (string) {
	if (typeof string !== 'string') {
		return string;
	}
	var ret = dic[string];
	return (ret === undefined || ret === '') ? string : ret;
};

var dic = {

	// ================= 职业 =================
	'Warrior': '战士',
	'Barbarian': '野蛮人',
	'Rogue': '盗贼',
	'Ranger': '游侠',
	'Duelist': '决斗者',
	'FireMage': '火法师',
	'StormMage': '风暴法师',
	'IceMage': '冰法师',
	'Necromancer': '死灵法师',
	'Enchanter': '幻术师',
	'Player': '玩家',

	// ================= 种族 =================
	'Human': '人类',
	'Ogre': '食人魔',
	'Troll': '巨魔',
	'Mummy': '木乃伊',
	'Elf': '精灵',
	'Gnome': '侏儒',
	'Gargoyle': '石像鬼',

	// ================= 宗教 =================
	'Exploration': '探索',
	'Health': '健康',
	'TheArcher': '游侠之神',
	'TheWizard': '法师之神',
	'Trog': '巨神特洛格',
	'Wealth': '财富',

	// ================= 技能 =================
	'Melee': '近战',
	'Fortitude': '坚韧',
	'Range': '远程',
	'Stealth': '潜行',
	'SpellCasting': '施法',
	'Focus': '专注',

	// ================= 伤害类型 =================
	'Fire': '火焰',
	'Cold': '冰霜',
	'Shock': '闪电',
	'Toxic': '毒素',
	'Physical': '物理',

	// ================= 属性名 =================
	'Block Projectile': '格挡飞弹',
	'Parry Melee': '招架近战',
	'Hit Points': '生命值',
	'Mana Points': '法力值',
	'Max Food': '最大饱食度',
	'EXP': '经验',
	'Protection': '护甲',
	'Fire Resistance': '火焰抗性',
	'Cold Resistance': '冰霜抗性',
	'Toxic Resistance': '毒素抗性',
	'Shock Resistance': '闪电抗性',
	'Evasion': '闪避',
	'Melee Power': '近战威力',
	'Range Power': '远程威力',
	'Fire Magic Power': '火焰法力威力',
	'Cold Magic Power': '冰霜法力威力',
	'Toxic Magic Power': '毒素法力威力',
	'Storm Magic Power': '风暴法力威力',
	'Spell Power': '法术威力',
	'Reflection': '反射',
	'Telepathy': '心灵感应',
	'Mana Regen': '法力回复',
	'Health Regen': '生命回复',
	'Melee Life Tap': '近战吸血',
	'Strength': '力量',
	'Dexterity': '敏捷',
	'Intelligence': '智力',
	'Damage Shield': '伤害护盾',
	'damage': '伤害',
	'duration': '持续',
	'numTraps': '陷阱数量',
	'maxPath': '最远距离',
	'aoeRange': '范围',
	'coldPower': '冰系威力',
	'damageMultiplier': '伤害倍数',
	'range': '范围',
	'stormPower': '风暴系威力',
	'stunTurns': '眩晕回合',
	'firePower': '火系威力',
	'skeletonLevel': '骷髅怪等级',
	'toxicPower': '毒系威力',

	// ================= 物品 =================
	'ArcheryGoggles': '弓箭护目镜',
	'BattleAxe': '战斧',
	'BearTrap': '捕兽夹',
	'BlueDragonScaleArmor': '蓝龙鳞甲',
	'BlueDragonScaleShield': '蓝龙鳞盾',
	'Bomb': '炸弹',
	'BootsOfFlight': '飞翔之靴',
	'BootsOfSpeed': '疾行之靴',
	'BootsOfStealth': '潜行靴',
	'BroadAxe': '阔斧',
	'Chakram': '环刃',
	'CharmOfClarity': '清晰护符',
	'CharmOfConfusion': '混乱护符',
	'CharmOfDisease': '疾病护符',
	'CharmOfEnergy': '能量护符',
	'CharmOfFire': '火焰护符',
	'CharmOfFreezing': '冰冻护符',
	'CharmOfHealing': '治疗护符',
	'CharmOfLightning': '闪电护符',
	'CharmOfRegeneration': '再生护符',
	'CharmOfSwiftness': '迅捷护符',
	'CircletOfKnowledge': '智慧头冠',
	'CloakOfStealth': '潜行斗篷',
	'ClothGloves': '布手套',
	'CrystalArmor': '水晶护甲',
	'Dart': '飞镖',
	'EnergyShroom': '能量蘑菇',
	'EnergyShroomTea': '能量蘑菇茶',
	'FirePot': '火油锅',
	'FireShroom': '火蘑菇',
	'Fists': '拳头',
	'FlamingHands': '烈焰之手',
	'GasPot': '毒气锅',
	'GauntletsOfStrength': '力量护手',
	'GlovesOfVampirism': '吸血手套',
	'GobletOfYendor': '延多之杯',
	'GoldCoin': '金币',
	'GreaterStaffOfFire': '强效火焰法杖',
	'GreaterStaffOfIce': '强效冰霜法杖',
	'GreaterStaffOfPoison': '强效毒素法杖',
	'GreaterStaffOfStorms': '强效风暴法杖',
	'GreenDragonScaleArmor': '绿龙鳞甲',
	'GreenDragonScaleShield': '绿龙鳞盾',
	'Halberd': '长戟',
	'HandAxe': '手斧',
	'Hat': '帽子',
	'HealingShroom': '治疗蘑菇',
	'HelmOfTelepathy': '心灵感应头盔',
	'InfernoRing': '地狱指环',
	'InfernoSword': '地狱之剑',
	'Javelin': '标枪',
	'Key': '钥匙',
	'LeatherArmor': '皮甲',
	'LeatherBoots': '皮靴',
	'LeatherGloves': '皮手套',
	'LeatherHelm': '皮盔',
	'LongBow': '长弓',
	'LongSword': '长剑',
	'Mace': '钉头锤',
	'Meat': '肉',
	'MetalShield': '金属盾',
	'MOB_FUCKER': '降龙杵',
	'MobFucker': '降龙杵',
	'OrbOfMana': '法力宝珠',
	'OrbOfPower': '力量宝珠',
	'PlateArmor': '板甲',
	'PlateBoots': '板靴',
	'PlateGloves': '板甲手套',
	'PlateHelm': '板盔',
	'PoisonDagger': '毒匕首',
	'PotionOfEnergy': '能量药剂',
	'PotionOfExperience': '经验药剂',
	'PotionOfGainAttribute': '属性提升药剂',
	'PotionOfHealing': '治疗药剂',
	'PotionOfLevitation': '漂浮药剂',
	'PotionOfPower': '力量药剂',
	'PotionOfResistance': '抗性药剂',
	'Rapier': '细剑',
	'RedDragonScaleArmor': '红龙鳞甲',
	'RedDragonScaleShield': '红龙鳞盾',
	'RingOfDexterity': '敏捷戒指',
	'RingOfEvasion': '闪避戒指',
	'RingOfFire': '火焰戒指',
	'RingOfFlight': '飞翔戒指',
	'RingOfHealth': '健康戒指',
	'RingOfIce': '冰霜戒指',
	'RingOfIntelligence': '智力戒指',
	'RingOfLearning': '求知戒指',
	'RingOfLifeSaving': '复活戒指',
	'RingOfMana': '法力戒指',
	'RingOfProtection': '守护戒指',
	'RingOfReflection': '反射戒指',
	'RingOfSpeed': '疾速戒指',
	'RingOfStealth': '潜行戒指',
	'RingOfStorm': '风暴戒指',
	'RingOfStrength': '力量戒指',
	'RingOfSustenance': '不饥戒指',
	'RingOfTheVampire': '吸血鬼戒指',
	'RingOfThunder': '雷霆戒指',
	'RingOfToxic': '毒素戒指',
	'RingOfWealth': '财富戒指',
	'RingOfWizardry': '秘法戒指',
	'Robe': '长袍',
	'RobeOfDeath': '死亡长袍',
	'RobeOfFlames': '烈焰长袍',
	'RobeOfIce': '冰霜长袍',
	'RobeOfStorms': '风暴长袍',
	'RobeOfWizardry': '秘法长袍',
	'ScrollOfAcquirement': '拾取卷轴',
	'ScrollOfBlink': '闪现卷轴',
	'ScrollOfDomination': '支配卷轴',
	'ScrollOfEnchantment': '附魔卷轴',
	'ScrollOfFear': '恐惧卷轴',
	'ScrollOfHellFire': '地狱火卷轴',
	'ScrollOfTeleportation': '传送卷轴',
	'ShieldOfReflection': '反射之盾',
	'Shoes': '鞋子',
	'ShortBow': '短弓',
	'ShortSword': '短剑',
	'Sling': '投石索',
	'Spear': '长矛',
	'SpikyShield': '尖刺盾',
	'Staff': '法杖',
	'StaffOfEnergy': '能量法杖',
	'StaffOfFire': '火焰法杖',
	'StaffOfIce': '冰霜法杖',
	'StaffOfMagicMissiles': '魔法飞弹法杖',
	'StaffOfPoison': '毒素法杖',
	'StaffOfPower': '力量法杖',
	'StaffOfStorms': '风暴法杖',
	'StormChopper': '风暴战斧',
	'ThrowingNet': '捕网',
	'TomeOfArchery': '弓术之书',
	'TomeOfAthletics': '运动之书',
	'TomeOfDeath': '死亡之书',
	'TomeOfDefense': '防御之书',
	'TomeOfEnchantment': '附魔之书',
	'TomeOfIce': '冰霜之书',
	'TomeOfInferno': '炼狱之书',
	'TomeOfPower': '力量之书',
	'TomeOfStealth': '潜行之书',
	'TomeOfStorms': '风暴之书',
	'TomeOfWar': '战争之书',
	'TwoHandSword': '双手剑',
	'WandOfBlades': '刃之魔杖',
	'WandOfBlinking': '闪现魔杖',
	'WandOfCold': '寒冰魔杖',
	'WandOfConfusion': '混乱魔杖',
	'WandOfDraining': '吸取魔杖',
	'WandOfFire': '火焰魔杖',
	'WandOfLightning': '闪电魔杖',
	'WarHammer': '战锤',
	'WhiteDragonScaleArmor': '白龙鳞甲',
	'WhiteDragonScaleShield': '白龙鳞盾',
	'WoodenShield': '木盾',

	// ================= 怪物 =================
	'AcidicSlime': '酸液史莱姆',
	'Ballista': '弩炮',
	'Bat': '蝙蝠',
	'BlinkFrog': '闪现蛙',
	'Bloat': '膨胀体',
	'BoaConstrictor': '巨蟒',
	'Bomber': '爆破者',
	'Bombomber': '哥布林爆破手',
	'BullFrog': '牛蛙',
	'CaveBear': '洞穴熊',
	'CentaurArcher': '半人马射手',
	'CentaurWarrior': '半人马战士',
	'Centipede': '蜈蚣',
	'Chameleon': '变色龙',
	'ClockworkArcher': '发条射手',
	'ClockworkFactory': '发条工厂',
	'ClockworkPyro': '发条纵火者',
	'ClockworkRat': '发条鼠',
	'ClockworkRhino': '发条犀牛',
	'ClockworkWarrior': '发条战士',
	'CorrosiveSlime': '腐蚀史莱姆',
	'Crate': '板条箱',
	'Crocodile': '鳄鱼',
	'CryptAltar': '墓穴祭坛',
	'CrystalGolem': '水晶魔像',
	"CylomarTheAncientPyromancer": '古代纵火法师赛洛玛',
	'DarkElfBladeDancer': '黑暗精灵刃舞者',
	'DarkElfPriest': '黑暗精灵祭司',
	'DarkElfPyromancer': '黑暗精灵纵火法师',
	'DarkElfSentinel': '黑暗精灵哨卫',
	'DarkElfStormologist': '黑暗精灵风暴学者',
	'DarkElfSummoner': '黑暗精灵召唤师',
	'DarkElfWarden': '黑暗精灵守卫',
	'DireWolf': '恐狼',
	'DireWolfKennel': '恐狼犬舍',
	'DrachnidArcher': '龙蛛射手',
	'DrachnidWarrior': '龙蛛战士',
	'ElectricEel': '电鳗',
	'Elephant': '大象',
	'EvilEye': '邪恶之眼',
	'FireBall': '火球',
	'FireBat': '火焰蝠',
	'FireBatNest': '火焰蝠巢',
	'FireElemental': '火焰元素',
	'FireImp': '火焰小鬼',
	'FireLizard': '火蜥蜴',
	'FirePot': '火油锅',
	'FireStaffTurret': '火焰法杖炮台',
	'FireStatue': '火焰雕像',
	'FleshGolem': '血肉魔像',
	'GasPot': '毒气锅',
	'GiantAnt': '巨型蚂蚁',
	'GiantBee': '巨型蜜蜂',
	'GiantLeach': '巨型水蛭',
	'Goat': '山羊',
	'GoblinArcher': '哥布林射手',
	'GoblinBomber': '哥布林爆破者',
	'GoblinBrute': '哥布林巨汉',
	'GoblinFireMage': '哥布林火法师',
	'GoblinShaman': '哥布林萨满',
	'GoblinStormMage': '哥布林风暴法师',
	'GoblinWarrior': '哥布林战士',
	'GreaterSpectralBlade': '巨型幽影刃',
	'HellHound': '地狱猎犬',
	'IceElemental': '冰霜元素',
	'IceImp': '冰霜小鬼',
	'IceStatue': '冰霜雕像',
	'InfernoOrb': '地狱球',
	'IronImp': '铁小鬼',
	'Jaguar': '美洲豹',
	'KasicTheMosquitoPrince': '蚊子王子卡西克',
	'KingMonRacar': '兽人国王蒙拉卡尔',
	"Mon'Racar The Orc King": '兽人国王蒙拉卡尔',
	'LavaEel': '熔岩鳗',
	'LickyToad': '舔舌蟾',
	'Maggot': '蛆虫',
	'MagicEye': '魔法之眼',
	'ManaViper': '法力蝰蛇',
	'Merchant': '商人',
	'Mosquito': '蚊子',
	'MummyPriest': '木乃伊祭司',
	'ObsidianGolem': '黑曜石魔像',
	'OgreShaman': '食人魔萨满',
	'OrbOfFire': '火焰宝珠',
	'OrcArcher': '兽人射手',
	'OrcFireMage': '兽人火法师',
	'OrcPriest': '兽人祭司',
	'OrcStormMage': '兽人风暴法师',
	'OrcSummoner': '兽人召唤师',
	'OrcWarrior': '兽人战士',
	'Penguin': '企鹅',
	'Pirahna': '食人鱼',
	'PoisonSpider': '毒蜘蛛',
	'PoisonViper': '毒蝰',
	'PolarBear': '北极熊',
	'PracticeDummy': '训练假人',
	'Priest': '祭司',
	'Rat': '老鼠',
	'RatNest': '鼠窝',
	'RottingCorpse': '腐烂尸体',
	'Scarab': '圣甲虫',
	'Scorpion': '蝎子',
	'Skeleton': '骷髅',
	'SkeletonArcher': '骷髅射手',
	'SkeletonWarrior': '骷髅战士',
	'SkillTrainer': '技能导师',
	'Slime': '史莱姆',
	'SnappingTurtle': '咬尾龟',
	'SpectralBlade': '幽影刃',
	'Spider': '蜘蛛',
	'SpiderEgg': '蜘蛛卵',
	'SpiderNest': '蜘蛛巢',
	'SpinyFrog': '刺蛙',
	'SpittingViper': '吐毒蝰',
	'StoneGolem': '石魔像',
	'StormElemental': '风暴元素',
	'StormImp': '风暴小鬼',
	'StormStatue': '风暴雕像',
	'Succubus': '魅魔',
	'SunFlower': '向日葵',
	'TalentTrainer': '天赋导师',
	'TentacleSpitter': '吐触手者',
	'TentacleTerror': '触手恐魔',
	'TheBridgeGuardian': '桥梁守卫',
	'TheLichKing': '巫妖王',
	'TheQueenSpider': '蜘蛛女王',
	'TheRatPiper': '鼠笛手',
	'TheVampireBat': '吸血蝠',
	'ToxicStatue': '毒素雕像',
	'TrapDoorSpider': '陷阱门蜘蛛',
	'Wolf': '野狼',
	'WolfKennel': '狼舍',
	'Wraith': '幽魂',
	'Yak': '牦牛',
	'ZombieBloat': '腐尸巨人',

	// ================= 场景物件 =================
	'Altar': '祭坛',
	'AltarOfExploration': '探索祭坛',
	'AltarOfHealth': '健康祭坛',
	'AltarOfTheArcher': '游侠祭坛',
	'AltarOfTheWizard': '法师祭坛',
	'AltarOfTrog': '特洛格祭坛',
	'AltarOfWealth': '财富祭坛',
	'AttributeFountain': '属性喷泉',
	'Barrel': '木桶',
	'Bars': '铁栏',
	'Bed': '床铺',
	'Bench': '长凳',
	'BigTable': '大桌',
	'Blood': '血迹',
	'Bones': '白骨',
	'BookShelf': '书架',
	'Brazer': '火盆',
	'Cactus': '仙人掌',
	'CampFire': '营火',
	'Candlabra': '烛台',
	'Casket': '石棺',
	'Chair': '椅子',
	'Chest': '宝箱',
	'CrystalChest': '水晶箱',
	'Door': '门',
	'DownStairs': '下行楼梯',
	'EnchantmentTable': '附魔台',
	'EnergyFountain': '能量喷泉',
	'ExperienceFountain': '经验喷泉',
	'Fern': '蕨草',
	'FireBallLauncher': '火球发射器',
	'FireGlyph': '火焰符文',
	'FireVent': '火焰喷口',
	'FishRack': '鱼架',
	'Flag': '旗帜',
	'Furnace': '熔炉',
	'GasLamp': '煤气灯',
	'GasVent': '毒气喷口',
	'Gate': '大门',
	'Generic': '杂物',
	'HealthFountain': '生命喷泉',
	'Ice': '冰块',
	'IceBomb': '冰爆弹',
	'InactiveFireVent': '已封闭的火焰喷口',
	'InactiveGasVent': '已封闭的毒气喷口',
	'LavaSpout': '熔岩喷口',
	'LavaTank': '熔岩池',
	'LightningRod': '避雷针',
	'LilyPads': '睡莲',
	'LongGrass': '高草',
	'MeatRack': '肉架',
	'Oil': '油',
	'OilTank': '油罐',
	'Pillar': '石柱',
	'Pipe': '管道',
	'PitTrap': '陷坑',
	'Portal': '传送门',
	'PressurePlate': '压力板',
	'Reeds': '芦苇',
	'Rock': '岩石',
	'Rubble': '瓦砾',
	'Scrap': '废料',
	'Shackles': '镣铐',
	'Shelf': '架子',
	'SkeletonCorpse': '骷髅残骸',
	'SkullStatue': '骷髅雕像',
	'SlimeTank': '史莱姆池',
	'SpiderWeb': '蜘蛛网',
	'SpikeTrap': '尖刺陷阱',
	'Stalagmite': '石笋',
	'Statue': '雕像',
	'SteamVent': '蒸汽喷口',
	'StepLadder': '梯子',
	'Stock': '刑架',
	'StoneBlocks': '石块',
	'StoneChips': '石屑',
	'StoneDoor': '石门',
	'StoneLavaSpout': '石制熔岩喷口',
	'Switch': '开关',
	'SwitchGate': '开关门',
	'Table': '桌子',
	'TeleportTrap': '传送陷阱',
	'Throne': '王座',
	'TikiTorch': '火把',
	'TimedGate': '定时门',
	'TimedSpikeTrack': '定时尖刺轨道',
	'TombStone': '墓碑',
	'Torch': '火把',
	'TransferanceTable': '附魔转移台',
	'Tree': '树',
	'UnfinishedGolem': '未完成的魔像',
	'UnlitBrazer': '未点燃的火盆',
	'UpStairs': '上行楼梯',
	'Vine': '藤蔓',
	'WallFlag': '墙上旗帜',
	'WaterStalagmite': '水中石笋',
	'WaterTree': '水中的树',
	'WellOfWishing': '许愿井',
	'WorkBench': '工作台',

	// ================= 能力 =================
	'Berserk': '狂暴',
	'BigExplode': '剧烈爆炸',
	'Blink': '闪现',
	'Bloat': '膨胀',
	'BreakGasPot': '打碎毒气锅',
	'Buffet': '猛击',
	'BurstOfFlame': '火焰爆发',
	'Cannibalise': '食人',
	'Charge': '冲刺',
	'Charm': '魅惑',
	'ColdAttunement': '冰霜亲和',
	'ConeOfCold': '冷锥',
	'Confusion': '困惑',
	'Constrict': '缠绕',
	'DeadEye': '死亡之眼',
	'Deflect': '偏转',
	'Disengage': '以退为进',
	'Domination': '支配',
	'DrainingAttack': '吸取攻击',
	'EXPDrainAttack': '吸取经验攻击',
	'Energy': '能量',
	'Evade': '金蝉脱壳',
	'Explode': '爆炸',
	'Fear': '恐惧',
	'FireAttunement': '火焰亲和',
	'FireBolt': '火焰枪',
	'FirePotExplode': '火油锅爆炸',
	'FireStorm': '火焰风暴',
	'FlamingCloudBolt': '烈焰云箭',
	'FlashFreeze': '急速冻结',
	'Freeze': '冻结',
	'FreezingCloud': '冻结云',
	'Haste': '加速',
	'Heal': '治疗',
	'Healing': '治疗中',
	'HellFire': '地狱火',
	'HideInShell': '缩入壳中',
	'IceArmor': '冰甲',
	'InfectiousDisease': '传染病',
	'Levitation': '漂浮',
	'LifeDrain': '生命汲取',
	'LifeSpike': '生命尖刺',
	'LightningBolt': '闪电箭',
	'Lunge': '死吻',
	'ManaDrainAttack': '吸取法力攻击',
	'MeleeAttack': '近战攻击',
	'Mesmerize': '催眠',
	'NPCCharm': '魅惑怪物',
	'NPCConfusion': '混乱怪物',
	'NPCPoisonCloud': '怪物毒云',
	'NimbleFingers': '灵活手指',
	'OrbOfFire': '火焰宝珠',
	'PlaceTrap': '放置陷阱',
	'PoisonAttack': '毒素攻击',
	'PoisonCloud': '毒云',
	'PoisonCloudBolt': '毒云箭',
	'PowerShot': '强弩',
	'PowerStrike': '强袭',
	'ProjectileAttack': '飞弹攻击',
	'ProjectileKite': '风筝飞弹',
	'ReviveSkeleton': '复活骷髅',
	'ScrollOfFear': '恐惧卷轴',
	'SealDoors': '封门',
	'ShieldsUp': '举盾',
	'Shock': '电击',
	'SleepingDart': '沉睡飞镖',
	'Slide': '滑行',
	'SlowCharge': '缓慢冲锋',
	'Smite': '神圣打击',
	'SmokeBomb': '烟雾弹',
	'Sneak': '潜行',
	'SpawnNPC': '召唤怪物',
	'Sprint': '疾跑',
	'StaticDischarge': '静电放电',
	'StormAttunement': '风暴亲和',
	'Suicide': '自爆',
	'SummonBlades': '召唤刃刃',
	'SummonIceBomb': '召唤冰爆弹',
	'SummonLightningRod': '召唤避雷针',
	'SummonMonsters': '召唤怪物',
	'SummonSkeleton': '召唤骷髅',
	'Swiftness': '迅捷',
	'ThrowBomb': '投掷炸弹',
	'ThrowNet': '投掷捕网',
	'ThunderClap': '雷霆一击',
	'TonguePull': '舌击拖拽',
	'ToxicAttunement': '毒系调和',
	'TrampleAttack': '践踏攻击',
	'TunnelShot': '量子穿透',
	'UseLightningRod': '使用避雷针',
	'VampireAttack': '吸血攻击',
	'WallOfFire': '火墙',
	'WallOfPoisonGas': '毒气墙',
	'WarCry': '战争呐喊',
	'WatchPlayer': '监视玩家',

	// ================= 天赋 =================
	'BloodLust': '嗜血',
	'ColdMastery': '冰系精通',
	'ColdResistance': '冰抗性',
	'DungeonSense': '地牢感知',
	'Evasive': '闪避',
	'FireMastery': '火系精通',
	'FireResistance': '火抗性',
	'Focus': '专注',
	'Fortitude': '坚韧不拔',
	'HeadShot': '猎杀',
	'KeenHearing': '千里眼',
	'MagicMastery': '法力精通',
	'PerfectAim': '完美瞄准',
	'RangeMastery': '远程精通',
	'Regeneration': '再生',
	'ShieldWall': '盾墙',
	'ShockResistance': '电抗性',
	'StealthMastery': '潜行精通',
	'StoneSkin': '岩石皮肤',
	'StormMastery': '风暴精通',
	'StrafeAttack': '扫射攻击',
	'ToxicMastery': '毒系精通',
	'ToxicResistance': '毒抗性',
	'Tranquility': '宁静',
	'WeaponMastery': '近战精通',

	// ================= 状态效果 =================
	'Bless': '祝福',
	'CastingFireStorm': '施放火焰风暴中',
	'CastingSmite': '施放神圣打击中',
	'Constricted': '被缠绕',
	'Constricting': '缠绕中',
	'DeepSleep': '沉睡',
	'Draining': '吸取中',
	'ExperienceBoost': '经验加成',
	'Feared': '恐惧',
	'Flammable': '易燃',
	'Frozen': '冻结',
	'Immobile': '无法移动',
	'Marked': '被标记',
	'Netted': '被网住',
	'Power': '强化',
	'Resistance': '抗性',
	'Slow': '缓慢',
	'StrongPoison': '剧毒',
	'Stunned': '眩晕',
	'Unstable': '站不稳',
	'Webbed': '被蛛网缠住',
	'Wet': '湿透',

	// ================= 区域 =================
	'TestLevel': '测试关卡',
	'TheArcaneTower': '奥秘之塔',
	'TheCore': '核心',
	'TheCrypt': '地下墓穴',
	'TheDarkTemple': '黑暗神殿',
	'TheIceCaves': '冰霜洞窟',
	'TheIronFortress': '钢铁要塞',
	'TheLichKingsLair': '巫妖王巢穴',
	'TheOrcFortress': '兽人要塞',
	'TheSewers': '下水道',
	'TheSunlessDesert': '无日荒漠',
	'TheSwamp': '沼泽',
	'TheUnderGrove': '地下林地',
	'TheUpperDungeon': '顶层地牢',
	'VaultOfYendor': '延多宝库',

	// ================= 地砖 =================
	'Bridge': '桥',
	'CaveFloor': '洞穴地板',
	'CavePit': '洞穴深坑',
	'Cave Wall': '洞壁',
	'Cave Floor': '洞穴地板',
	'CaveWall': '洞壁',
	'Floor': '地板',
	'HalfWall': '半墙',
	'Lava': '熔岩',
	'Pit': '深坑',
	'ToxicWaste': '毒液',
	'Wall': '墙壁',
	'Water': '水',

	// ================= 云 / 法术区域 =================
	'Dust': '尘土',
	'FlamingCloud': '烈焰云',
	'PoisonGas': '毒气',
	'Smoke': '雾气',
	'SmokeBomb': '烟雾弹',
	'Steam': '蒸汽',
	'WhiteSmoke': '白烟',

	// ================= 投射物 =================
	'Acid': '强酸',
	'FireArrow': '火焰箭',
	'IceArrow': '冰霜箭',
	'MagicMissile': '魔法飞弹',
	'Net': '捕网',
	'PlayerBomb': '玩家炸弹',
	'PlayerGasBall': '玩家毒气球',
	'PoisonArrow': '毒箭',
	'PoisonGasBall': '毒气球',
	'SlimeBomb': '史莱姆炸弹',
	'Snowball': '雪球',
	'Spark': '火花',
	'SparkBall': '火花球',
	'Stone': '石块',
	'StrongPoisonArrow': '剧毒箭',

	// ================= 武器效果 =================
	'Cleave': '横扫',
	'Flame': '火焰',
	'MagicStaff': '魔法杖击',
	'PoleArm': '长柄武器',
	'SingleProjectile': '单发投掷',
	'StormChopper': '风暴斩',

	// ================= 物品效果 =================
	'Eat': '食用',
	'Teleportation': '传送',

	// ================= NPC 特性 =================
	'Blinking': '闪现',
	'Fast': '迅捷',
	'Regenerating': '再生',
	'Spiny': '多刺',
	'Strong': '强壮',
	'Tough': '坚韧',

	// ================= 战斗 / 状态飘字 =================
	'Fully Healed': '生命完全恢复',
	'Already full health': '生命值已满',
	'Full Energy': '法力完全恢复',
	'Already full energy': '法力值已满',
	'+4 Max HP': '+4 最大生命值',
	'+1 Max MP': '+1 最大法力值',
	'+1 Skill Point': '+1 技能点',
	'+1 Talent Point': '+1 天赋点',
	'+1 ': '+1 ',
	' skill': ' 点技能',
	' available': ' 点可用',
	'Teleport!': '传送！',
	'Frozen!': '冻结！',
	'Fear!': '恐惧！',
	'Charmed!': '被魅惑！',
	'Healed!': '治疗完成！',
	'Life Drain': '生命汲取',
	'Casting Heal': '施放治疗中',
	'Casting Haste': '施放加速中',
	'Mana Drain!': '吸取法力！',
	'Trample!': '践踏！',
	'Revive Skeleton': '复活骷髅',
	'Revived': '已复活',
	'Summoned': '已召唤',
	'Immune': '免疫',
	'Sleeping': '沉睡中',
	'HUNGRY': '饥饿',
	'Sealed': '已封锁',
	'Parry': '招架',
	'Miss': '未命中',
	'MISS': '未命中',
	'REFLECT': '反射',
	'Poof': '噗',
	'Summon Ice Bomb': '召唤冰爆弹',
	'Summon Lightning Rod': '召唤避雷针',
	'Poison Cloud': '毒云',
	'Lightning Rod': '避雷针',
	'Orb of Fire': '火焰宝珠',
	'Slide!': '滑行！',
	'Buffet!': '猛击！',
	'Ambush!': '伏击！',
	'Running!': '逃跑！',
	'Poisoned!': '中毒了！',
	'Crit -': '暴击 -',
	'Blocked!': '格挡！',
	'Reposte!': '招架！',
	'Saved Ammo': '节省弹药',
	'Out of Ammo': '弹药耗尽',
	'Pit Trap!': '陷坑！',
	'Teleport Trap!': '传送陷阱！',
	'VERY HUNGRY': '非常饥饿！',
	'Cant run!': '无法冲刺！',
	'Fell down pit!': '掉进坑里了！',
	'Inventory Full': '背包已满',
	'Really jump into the pit?': '真的要跳进坑里吗？',
	'No charge': '无充能',
	'Saved Mana': '节省法力',
	'Cannot Eat': '无法食用',
	'LEVEL UP': '升级！',
	'Dangerous Terrain': '危险地形',
	'Corroded ': '腐蚀的',
	'REST ': '休息 ',
	' off': ' 关',
	' on': ' 开',
	'charged': ' 充能中',
	' -> ': ' → ',

	// ================= HUD 提示 =================
	'Use s or > to descend stairs': '按 s 或 > 下楼',
	'Use s or < to ascend stairs': '按 s 或 < 上楼',

	// ================= 对话错误提示 =================
	'DialogError: Missing text list, did you spell it wrong AGAIN?': '对话错误：缺少文本列表，你又拼错了吗？',
	'DialogError: Missing responses list, did you spell it wrong AGAIN?': '对话错误：缺少回复列表，你又拼错了吗？',
	'No Dialog (did you forget a default in the init function?': '没有对话（你忘了在 init 函数里设置默认值吗？）',

	// ================= 界面文案 =================
	'Charges: ': '充能: ',
	'\nCharges: ': '\n充能: ',
	' Gold': ' 金币',
	' Gold Each': ' 金币/个',
	' KB': ' KB',
	' Would you like to join this religion?': ' 你要皈依这个信仰吗？',
	' charged': ' 充能中',
	' off': ' 关',
	' on': ' 开',
	' successfully retrieved the Goblet of Yendor in ': ' 成功在以下时间取得延多之杯: ',
	' to ': ' 至 ',
	' x ': ' x ',
	'+1 Dex': '+1 敏捷',
	'+1 Int': '+1 智力',
	'+1 Str': '+1 力量',
	'. You are already worshipping a god!': '。你已经信仰其它神明了！',
	'Best Win Time: ': '最佳通关时间: ',
	'Blocked!': '格挡！',
	'Buy: ': '购买: ',
	'Cannot Eat': '无法食用',
	'Cannot load object, unknown typeFrame: ': '无法加载物件，未知的 typeFrame: ',
	'Cant run!': '无法冲刺！',
	'Click Inventory: use/equip an item.': '点击背包：使用/装备物品。',
	'Click Mini Map: move to.': '点击小地图：移动到该处。',
	'Click Self: wait a turn.': '点击自己：等待一回合。',
	'Click Tile: move, attack, interact.': '点击地砖：移动、攻击、互动。',
	'Cold:': '冰霜: ',
	'Corroded ': '腐蚀的',
	'Cost: ': '消耗: ',
	'Crit -': '暴击 -',
	'Daily Challenge': '每日挑战',
	'Daily Challenge Complete for: ': '每日挑战完成度: ',
	'Dangerous Terrain': '危险地形',
	'Empty (0 KB)': '空 (0 KB)',
	'Enchant Item': '附魔物品',
	'Enchanted ': '已附魔的',
	'Error: cannot descent on this level': '错误：本层无法下降',
	'Fastest Win Time: ': '最快通关时间: ',
	'Fastest win Time: ': '最快通关时间: ',
	'Fell down pit!': '掉进坑里了！',
	'Fire:': '火焰: ',
	'General Advice': '通用建议',
	'Hello World': '你好，世界',
	"I'll give you ": '我给你 ',
	'Instant Respawn (Testing)': '立即复活（测试）',
	'Inventory Full': '背包已满',
	'KEYBOARD CONTROLS:': '键盘操作:',
	'Keyboard Conrols': '键盘操作',
	'LEVEL UP': '升级！',
	'MOUSE CONTROLS:': '鼠标操作:',
	'Mouse Controls': '鼠标操作',
	'No charge': '无充能',
	'NumPad: 8-way move, attack, interact.': '小键盘：八方向移动、攻击、互动。',
	'NumPad[5]: wait a turn.': '小键盘[5]：等待一回合。',
	'Player Inventory': '玩家背包',
	'Poisoned!': '中毒了！',
	'REST ': '休息 ',
	'Really jump into the pit?': '真的要跳进坑里吗？',
	'Reflective\n': '反射\n',
	'Reposte!': '招架！',
	'Saved Mana': '节省法力',
	'Select an item type to randomly summon.': '选择一种物品类型进行随机召唤。',
	'Sell: ': '出售: ',
	'Shop Inventory': '商店库存',
	'Storm:': '风暴: ',
	'Summon Item': '召唤物品',
	'Toxic:': '毒素: ',
	'Transfer Enchantment': '转移附魔',
	'Use Item': '使用物品',
	'VERY HUNGRY': '非常饥饿！',
	'Win 2 daily challenges in a row.': '连续完成2次每日挑战。',
	'Win 3 daily challenges in a row.': '连续完成3次每日挑战。',
	'Win 5 daily challenges in a row.': '连续完成5次每日挑战。',
	'You pray at the altar of ': '你在下列祭坛前祈祷: ',
	'Your level ': '你的等级 ',
	'[A]: Ranged targeting, NumPad[5] to confirm.': '[A]：远程定位，小键盘[5]确认。',
	'[E]: Explore automatically.': '[E]：自动探索。',
	'[R]: Recast previous spell.': '[R]：重复施放上一个法术。',
	'[W]: Wield previous weapon.': '[W]：切换到上一把武器。',
	'- Flying\n': '- 飞行\n',
	'- Life Saving\n': '- 复活\n',
	'- Telepathic\n': '- 心灵感应\n',
	'Default Text': '默认文本',
	'No Dialog (did you forget a default in the init function?': '没有对话（你忘了在 init 函数里设置默认值吗？）',
	'successfully retrieved the Goblet of Yendor': '成功取得延多之杯',
	'Zoning from ': '正在前往 ',
	'level ': '层，',
	'loading game records': '正在读取游戏记录',
	'creating game record...': '正在创建游戏记录...',
	'attempting to send stats to server...': '正在上传统计数据...',

	// ================= 帮助文本 =================
	'Waiting a turn is a good way to get enemies to position themselves optimally. Its often better to find a good position and let them come to you.':
		'等待一回合是让敌人自己走到最佳位置的好办法。通常更好的做法是先找一个好位置，让敌人来找你。',
	'Water, rubble, vines and other surfaces provide an unstable footing. Any character, including yourself who is unstable is automatically critically hit.':
		'水域、瓦砾、藤蔓等地面会让人站不稳。任何处于不稳定状态的角色（包括你自己）都会被自动暴击。',
	'Your healing items are precious. You get full hp upon leveling and also when you find restoration tanks in dungeons. Try to conserve your consumables as much as possible.':
		'你的治疗物品非常珍贵。升级时以及在地牢中找到恢复池时都会回满生命值。尽量节省你的消耗品。',
	'Your spear has a 2 tile range, you should be able to get a free hit on most enemies.':
		'你的长矛有2格攻击距离，应该可以对大多数敌人进行无伤攻击。'
};

// 非精确匹配：处理“+3 ShortSword”“Buying LongSword”之类的拼接串。
// 只在整串不是已知键、且其中确实包含已知键时才启用，避免误伤普通英文。
translator.getTextLoose = function (string) {
	if (typeof string !== 'string' || string === '' || dic[string]) {
		return string;
	}

	// 形如 "+3 ShortSword" / "+3 LongSword" 的强化前缀
	var mod = /^([+-]\d+)\s+([A-Za-z][A-Za-z0-9_]*)$/.exec(string);
	if (mod && dic[mod[2]]) {
		return mod[1] + ' ' + dic[mod[2]];
	}

	// 形如 "x3 ShortSword"
	var count = /^x(\d+)\s+([A-Za-z][A-Za-z0-9_]*)$/.exec(string);
	if (count && dic[count[2]]) {
		return 'x' + count[1] + ' ' + dic[count[2]];
	}

	return string;
};

// 对外统一的入口：先精确、后宽松
translator.translate = function (string) {
	return translator.getTextLoose(translator.getText(string));
};

// 词库规模（调试用）
translator.size = function () {
	var n = 0;
	for (var k in dic) {
		if (dic.hasOwnProperty(k)) {
			n += 1;
		}
	}
	return n;
};
